import React from 'react'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About Page',
  description: 'Generated by create next app',
}


const About = () => {
  return (
    <div>About Page</div>
  )
}

export default About
