import AddProduct from "./addProduct";
import DeleteProduct from "./deleteProduct";
import UpdateProduct from "./updateProduct";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Product Page',
  description: 'Generated by create next app',
}

type product = {
  id: number;
  title: string;
  price: number;
};

async function getProduct() {
  const res = await fetch("http://localhost:5000/product", {cache: "no-store"});
  return res.json();
}

export default async function Product() {
  const products: product[] = await getProduct();
  return (
    <div className="py-10 px-10">
        <div className="py-2">
            <AddProduct />
        </div>
      <table className="table w-full">
        <thead>
          <tr className="bg-slate-700">
            <th>#</th>
            <th>Product Name</th>
            <th>Price</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
            
        {products.map((product, index) => (
            <tr key={product.id}>
                <td>{index + 1}</td>
                <td>{product.title}</td>
                <td>{product.price}</td>
                <td className="flex">
                    <UpdateProduct {...product}/>
                    <DeleteProduct {...product}/>
                </td>
            </tr>
        ))}
            
        </tbody>
      </table>
    </div>
  );
}
